'use strict';
// Winter town gameplay. Handmade low-poly horses and weapons use no external assets.
const horses=[],arrows=[];
let mountedHorse=null,weapon='axe',weaponCooldown=0,horseTime=0;
Object.assign(state,{hasBow:false,hasSpear:false,arrows:0});
const weaponRecipes={bow:{label:'قوس',cost:{wood:6,fiber:5}},spear:{label:'رمح',cost:{wood:3,stone:2,fiber:1}},arrows:{label:'5 سهام',cost:{wood:2,stone:1,fiber:1}}};
const leather=new THREE.MeshStandardMaterial({color:0x34251e,roughness:1}),steel=new THREE.MeshStandardMaterial({color:0xadbfc8,metalness:.5,roughness:.4});
function cylinderBetween(group,a,b,r,material){const delta=b.clone().sub(a),mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,delta.length(),7),material);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());group.add(mesh);return mesh;}
function horseModel(color){const g=new THREE.Group(),coat=new THREE.MeshStandardMaterial({color,roughness:.95});
 function ellipsoid(x,y,z,sx,sy,sz,mat=coat){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;g.add(m);return m;}
 ellipsoid(0,1.35,0,.43,.52,.86);ellipsoid(0,1.75,-.65,.28,.65,.29).rotation.x=-.4;ellipsoid(0,2.19,-.92,.23,.31,.43);ellipsoid(0,2.02,-1.23,.2,.19,.26);
 for(const x of [-.15,.15]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.09,.33,5),coat);ear.position.set(x,2.54,-.87);g.add(ear);ellipsoid(x*1.52,2.25,-1,.036,.043,.034,leather);}
 ellipsoid(0,1.4,.91,.1,.53,.12,leather).rotation.x=.25;
 for(let i=0;i<5;i++)ellipsoid(0,1.7+i*.16,-.45-i*.075,.11,.17,.12,leather);
 const legs=[];for(const x of [-.3,.3])for(const z of [-.55,.55]){const leg=new THREE.Group();leg.position.set(x,1.25,z);g.add(leg);addBox(leg,.15,.98,.17,0,-.47,0,coat);addBox(leg,.19,.17,.26,0,-1.05,-.025,leather);legs.push(leg);}
 addBox(g,.73,.15,.68,0,1.83,.05,leather);addBox(g,.76,.22,.1,0,1.92,.36,leather);for(const x of [-.47,.47]){cylinderBetween(g,new THREE.Vector3(x,1.8,0),new THREE.Vector3(x,1.13,0),.024,leather);addBox(g,.13,.05,.18,x,1.12,0,steel);}
 g.userData.legs=legs;return g;
}
function horseSpot(x,z){for(let r=0;r<15;r+=1)for(let i=0;i<16;i++){const px=x+Math.cos(i*Math.PI/8)*r,pz=z+Math.sin(i*Math.PI/8)*r,h=heightAt(px,pz);if(h!==null&&[-.7,.7].every(dx=>[-1,1].every(dz=>heightAt(px+dx,pz+dz)!==null))&&!isWorldBlocked(px,pz))return new THREE.Vector3(px,h,pz);}return null;}
window.initializeWinter=function(){if(horses.length)return;for(let i=0;i<3;i++){const p=horseSpot(player.pos.x+3+i*5,player.pos.z+2);if(!p)continue;const mesh=horseModel([0x805136,0x44372f,0xb19a80][i]);mesh.position.copy(p);scene.add(mesh);horses.push({mesh,pos:mesh.position,phase:i});}};
function nearestHorse(){return horses.filter(h=>Math.hypot(h.pos.x-player.pos.x,h.pos.z-player.pos.z)<3.5).sort((a,b)=>a.pos.distanceTo(player.pos)-b.pos.distanceTo(player.pos))[0];}
function toggleMount(){if(buildMode)return false;if(mountedHorse){let p=null;for(const side of [-1,1]){const x=player.pos.x+Math.cos(player.yaw)*side*1.7,z=player.pos.z-Math.sin(player.yaw)*side*1.7,y=heightAt(x,z);if(y!==null&&!isWorldBlocked(x,z)){p=new THREE.Vector3(x,y+1.7,z);break;}}if(!p){showFeedback('تحرك إلى مكان أوسع للنزول');return false;}mountedHorse=null;player.speed=5.5;player.pos.copy(p);showFeedback('نزلت من الحصان');}
 else{const h=nearestHorse();if(!h){showFeedback('اقترب من حصان ثم اضغط G');return false;}mountedHorse=h;player.pos.copy(h.pos);player.pos.y+=1.7;player.yaw=h.mesh.rotation.y;player.speed=10;showFeedback('ركبت الحصان — Shift للعدو · G للنزول');}saveGame();return true;}
function weaponModel(kind){const g=new THREE.Group();if(kind==='bow'){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,-.6,0),new THREE.Vector3(0,-.3,-.2),new THREE.Vector3(0,0,-.26),new THREE.Vector3(0,.3,-.2),new THREE.Vector3(0,.6,0)]);g.add(new THREE.Mesh(new THREE.TubeGeometry(curve,16,.028,5,false),woodMaterial));cylinderBetween(g,new THREE.Vector3(0,-.6,0),new THREE.Vector3(0,.6,0),.006,ropeMaterial);}
 else{cylinderBetween(g,new THREE.Vector3(0,0,.65),new THREE.Vector3(0,0,-1.05),.025,woodMaterial);const head=new THREE.Mesh(new THREE.ConeGeometry(kind==='spear'?.085:.035,.27,4),steel);head.rotation.x=-Math.PI/2;head.position.z=-1.16;g.add(head);}return g;}
const heldBow=weaponModel('bow'),heldSpear=weaponModel('spear');camera.add(heldBow,heldSpear);heldBow.position.set(.32,-.2,-.65);heldSpear.position.set(.35,-.3,-.45);
const thirdWeapon=new THREE.Group();scene.add(thirdWeapon);const thirdBow=weaponModel('bow'),thirdSpear=weaponModel('spear');thirdWeapon.add(thirdBow,thirdSpear);
function craftWeapon(kind){const recipe=weaponRecipes[kind];if(!recipe||(kind==='bow'&&state.hasBow)||(kind==='spear'&&state.hasSpear)||!pay(recipe.cost))return false;if(kind==='arrows')state.arrows+=5;else{state[kind==='bow'?'hasBow':'hasSpear']=true;weapon=kind;}Audio.build();saveGame();return true;}
const winterRenderPanel=renderPanel;renderPanel=function(message=''){winterRenderPanel(message);if(panelMode!=='inventory')return;const section=document.createElement('div');section.innerHTML='<h3>القوس والرمح</h3><p>Q لتبديل السلاح · نقرة للهجوم · سهام: '+state.arrows+'</p><div class="recipe-grid">'+Object.entries(weaponRecipes).map(([k,r])=>{const made=k==='bow'?state.hasBow:k==='spear'?state.hasSpear:false;return '<article class="recipe-card"><h3>'+r.label+'</h3><p>'+costText(r.cost)+'</p><button data-weapon="'+k+'" '+(made||!affordable(r.cost)?'disabled':'')+'>'+(made?'تمت الصناعة':'اصنع')+'</button></article>';}).join('')+'</div>';panel.querySelector('.survival-window').appendChild(section);for(const b of section.querySelectorAll('button'))b.onclick=()=>{const ok=craftWeapon(b.dataset.weapon);renderPanel(ok?'تمت الصناعة':'الموارد غير كافية');};};
function attack(){if(weaponCooldown>0||settingsOpen||buildMode||!state.started||state.gameOver)return false;const origin=player.pos.clone();origin.y+=mountedHorse?.9:-.15;const direction=new THREE.Vector3(-Math.sin(player.yaw)*Math.cos(player.pitch),Math.sin(player.pitch),-Math.cos(player.yaw)*Math.cos(player.pitch));
 // Camera positive pitch looks down in Three.js.
 direction.y=-Math.sin(player.pitch);
 if(weapon==='bow'){if(!state.hasBow)return false;if(state.arrows<1){showFeedback('اصنع سهامًا من الحقيبة Tab');return false;}state.arrows--;const mesh=weaponModel('arrow');mesh.scale.setScalar(.48);mesh.position.copy(origin);scene.add(mesh);arrows.push({mesh,velocity:direction.multiplyScalar(32),life:4});weaponCooldown=.65;Audio.chop();saveGame();return true;}
 if(weapon==='spear'){if(!state.hasSpear)return false;weaponCooldown=.65;const hit=animals.map(a=>({a,v:a.pos.clone().add(new THREE.Vector3(0,.55,0)).sub(origin)})).filter(o=>o.v.length()<3.8&&o.v.clone().normalize().dot(direction)>.72).sort((a,b)=>a.v.length()-b.v.length())[0];if(hit)huntAnimal(hit.a);Audio.chop();return true;}
 return interact();
}
function advanceArrows(dt){for(let i=arrows.length-1;i>=0;i--){const a=arrows[i],from=a.mesh.position.clone(),to=from.clone().addScaledVector(a.velocity,dt),segment=to.clone().sub(from),length=segment.length();let remove=false,closest=Infinity,target=null;
 const ray=new THREE.Raycaster(from,segment.clone().normalize(),0,length);const walls=ray.intersectObjects(structures.map(s=>s.mesh),true);if(walls.length)closest=walls[0].distance;
 // Small steps prevent arrows crossing a building or hillside between frames.
 for(let t=0;t<=length;t+=.15){const p=from.clone().addScaledVector(ray.ray.direction,t),h=citySample(p.x,p.z,false);if(h!==null&&p.y<h+.08){closest=Math.min(closest,t);break;}}
 for(const animal of animals){const center=animal.pos.clone().add(new THREE.Vector3(0,.55,0)),along=center.clone().sub(from).dot(ray.ray.direction);if(along<0||along>length||along>=closest)continue;if(ray.ray.at(along,new THREE.Vector3()).distanceTo(center)<.7){closest=along;target=animal;}}
 if(closest<=length){if(target)huntAnimal(target);remove=true;}a.mesh.position.copy(to);a.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),a.velocity.clone().normalize());a.velocity.y-=5*dt;a.life-=dt;if(a.life<=0)remove=true;if(remove){scene.remove(a.mesh);a.mesh.traverse(o=>{if(o.isMesh)o.geometry.dispose();});arrows.splice(i,1);}}
}
const oldUpdatePlayer=updatePlayer;updatePlayer=function(dt){player.speed=mountedHorse?10:5.5;const before=player.pos.clone();const steps=Math.max(1,Math.ceil(dt/.02));for(let i=0;i<steps;i++)oldUpdatePlayer(dt/steps);if(mountedHorse){mountedHorse.pos.set(player.pos.x,player.pos.y-1.7,player.pos.z);mountedHorse.mesh.rotation.y=player.yaw;const moving=before.distanceTo(player.pos)>.001;mountedHorse.mesh.userData.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(horseTime*12+(i===0||i===3?0:Math.PI))*.65:0);camera.position.y+=.9;}
 axeGroup.visible=axeGroup.visible&&weapon==='axe';heldBow.visible=state.started&&preferences.perspective==='first'&&weapon==='bow';heldSpear.visible=state.started&&preferences.perspective==='first'&&weapon==='spear';heldSpear.position.z=-.45-Math.sin(Math.max(0,weaponCooldown)/.65*Math.PI)*.45;
 thirdWeapon.visible=state.started&&preferences.perspective==='third';thirdBow.visible=weapon==='bow';thirdSpear.visible=weapon==='spear';thirdWeapon.position.set(player.pos.x+Math.cos(player.yaw)*.38,player.pos.y-.55+(mountedHorse?.85:0),player.pos.z-Math.sin(player.yaw)*.38);thirdWeapon.rotation.set(0,player.yaw,0);
};
const winterAvatar=updateAvatar;updateAvatar=function(dt,moving){winterAvatar(dt,mountedHorse?false:moving);if(mountedHorse&&avatar){avatar.position.y+=.78;avatar.traverse(b=>{if(!b.isBone)return;if(/LeftUpLeg$/.test(b.name))b.rotation.set(-1.05,0,.22);if(/RightUpLeg$/.test(b.name))b.rotation.set(-1.05,0,-.22);if(/(Left|Right)Leg$/.test(b.name))b.rotation.x=1.25;});}};
const snowGeometry=new THREE.BufferGeometry(),snowPositions=new Float32Array(600*3);for(let i=0;i<600;i++){snowPositions[i*3]=(Math.random()-.5)*65;snowPositions[i*3+1]=Math.random()*22;snowPositions[i*3+2]=(Math.random()-.5)*65;}snowGeometry.setAttribute('position',new THREE.BufferAttribute(snowPositions,3));const snow=new THREE.Points(snowGeometry,new THREE.PointsMaterial({color:0xffffff,size:.065,transparent:true,opacity:.8,depthWrite:false}));scene.add(snow);
const winterUpdate=window.updateSurvivalSystems;window.updateSurvivalSystems=function(dt){winterUpdate(dt);horseTime+=dt;weaponCooldown=Math.max(0,weaponCooldown-dt);advanceArrows(dt);snow.position.set(player.pos.x,player.pos.y-3,player.pos.z);for(let i=0;i<600;i++){snowPositions[i*3+1]-=dt*(1.1+i%3*.3);if(snowPositions[i*3+1]<0)snowPositions[i*3+1]=22;}snowGeometry.attributes.position.needsUpdate=true;};
const winterSync=syncUI;syncUI=function(){winterSync();if(!state.started)return;toolStatus.textContent+=(weapon==='bow'?' · 🏹 قوس · '+state.arrows+' سهم':weapon==='spear'?' · رمح':'')+' · Q تبديل'+(mountedHorse?' · G نزول':'');if(!settingsOpen&&!buildMode&&(mountedHorse||nearestHorse())){ui.prompt.textContent=mountedHorse?'G — النزول من الحصان':'G — ركوب الحصان';ui.prompt.style.opacity='1';}};
window.winterSave=()=>({hasBow:state.hasBow,hasSpear:state.hasSpear,arrows:state.arrows,weapon,horses:horses.map(h=>({x:h.pos.x,z:h.pos.z,yaw:h.mesh.rotation.y}))});
window.winterLoad=function(data){mountedHorse=null;player.speed=5.5;if(!data)return;state.hasBow=!!data.hasBow;state.hasSpear=!!data.hasSpear;state.arrows=Number.isFinite(data.arrows)?Math.max(0,Math.floor(data.arrows)):0;weapon=data.weapon==='bow'&&state.hasBow?'bow':data.weapon==='spear'&&state.hasSpear?'spear':'axe';for(const [i,r]of (data.horses||[]).entries()){if(!horses[i]||!Number.isFinite(r.x)||!Number.isFinite(r.z))continue;const y=heightAt(r.x,r.z);if(y!==null){horses[i].pos.set(r.x,y,r.z);horses[i].mesh.rotation.y=Number.isFinite(r.yaw)?r.yaw:0;}}};
window.addEventListener('keydown',e=>{if(!state.started||state.gameOver||settingsOpen||e.repeat)return;if(e.code==='KeyG'){e.preventDefault();toggleMount();}if(e.code==='KeyQ'&&!buildMode){e.preventDefault();const list=['axe',...(state.hasBow?['bow']:[]),...(state.hasSpear?['spear']:[])];weapon=list[(list.indexOf(weapon)+1)%list.length];showFeedback(weapon==='bow'?'القوس — نقرة لإطلاق سهم':weapon==='spear'?'الرمح — نقرة للطعن':'الفأس / اليد');}},true);
renderer.domElement.addEventListener('click',()=>{if(pointerLocked&&!buildMode)attack();});
heldBow.visible=false;heldSpear.visible=false;thirdWeapon.visible=false;
if(forestReady)initializeWinter();

